version: '3.8'
services:
  postgres_db:
    image: postgres:latest
    container_name: dsptracker_postgres
    restart: always
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: dsptracker_pgadmin
    restart: always
    ports:
      - "8888:80"
    env_file:
      - ./.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  postgres_db:
  pgadmin-data: